import { Navbar } from "@/components/Navbar";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazirMatn = Vazirmatn({
  subsets: ["arabic"],
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={vazirMatn.className}>
      <body className="bg-background ">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
